import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({ subsets: ['latin'], weight: ['100', '400', '700'] });

export const metadata = {
  title: 'Effective Buddhism',
  description: 'Generated by Persist Ventures',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
